<?php

namespace PowerTranz\Support;

class IsoCodes
{
    const ISO_COUNTRY_CODES = [
        ['Afghanistan','004','AF','AFG'],
        ['Aland Islands','248','AX','ALA'],
        ['Albania','008','AL','ALB'],
        ['Algeria','012','DZ','DZA'],
        ['American Samoa','016','AS','ASM'],
        ['Andorra','020','AD','AND'],
        ['Angola','024','AO','AGO'],
        ['Anguilla','660','AI','AIA'],
        ['Antarctica','010','AQ','ATA'],
        ['Antigua and Barbuda','028','AG','ATG'],
        ['Argentina','032','AR','ARG'],
        ['Armenia','051','AM','ARM'],
        ['Aruba','533','AW','ABW'],
        ['Australia','036','AU','AUS'],
        ['Austria','040','AT','AUT'],
        ['Azerbaijan','031','AZ','AZE'],
        ['Bahamas','044','BS','BHS'],
        ['Bahrain','048','BH','BHR'],
        ['Bangladesh','050','BD','BGD'],
        ['Barbados','052','BB','BRB'],
        ['Belarus','112','BY','BLR'],
        ['Belgium','056','BE','BEL'],
        ['Belize','084','BZ','BLZ'],
        ['Benin','204','BJ','BEN'],
        ['Bermuda','060','BM','BMU'],
        ['Bhutan','064','BT','BTN'],
        ['Bolivia, Plurinational State of','068','BO','BOL'],
        ['Bonaire Sint Eustatius and Saba','535','BQ','BES'],
        ['Bosnia and Herzegovina','070','BA','BIH'],
        ['Botswana','072','BW','BWA'],
        ['Bouvet Island','074','BV','BVT'],
        ['Brazil','076','BR','BRA'],
        ['British Indian Ocean Territory','086','IO','IOT'],
        ['Brunei Darussalam','096','BN','BRN'],
        ['Bulgaria','100','BG','BGR'],
        ['Burkina Faso','854','BF','BFA'],
        ['Burundi','108','BI','BDI'],
        ['Cambodia','116','KH','KHM'],
        ['Cameroon','120','CM','CMR'],
        ['Canada','124','CA','CAN'],
        ['Cape Verde','132','CV','CPV'],
        ['Cayman Islands','136','KY','CYM'],
        ['Central African Republic','140','CF','CAF'],
        ['Chad','148','TD','TCD'],
        ['Chile','152','CL','CHL'],
        ['China','156','CN','CHN'],
        ['Christmas Island','162','CX','CXR'],
        ['Cocos (Keeling) Islands','166','CC','CCK'],
        ['Colombia','170','CO','COL'],
        ['Comoros','174','KM','COM'],
        ['Congo','178','CG','COG'],
        ['Congo, Democratic Republic of','180','CD','ZAR'],
        ['Cook Islands','184','CK','COK'],
        ['Costa Rica','188','CR','CRI'],
        ['Côte d’Ivoire','384','CI','CIV'],
        ['Croatia','191','HR','HRV'],
        ['Cuba','192','CU','CUB'],
        ['Curacao','531','CW','CUW'],
        ['Cyprus','196','CY','CYP'],
        ['Czech Republic','203','CZ','CZE'],
        ['Denmark','208','DK','DNK'],
        ['Djibouti','262','DJ','DJI'],
        ['Dominica','212','DM','DMA'],
        ['Dominican Republic','214','DO','DOM'],
        ['Ecuador','218','EC','ECU'],
        ['Egypt','818','EG','EGY'],
        ['El Salvador','222','SV','SLV'],
        ['Equatorial Guinea','226','GQ','GNQ'],
        ['Eritrea','232','ER','ERI'],
        ['Estonia','233','EE','EST'],
        ['Ethiopia','230','ET','ETH'],
        ['Falkland Islands (Malvinas)','238','FK','FLK'],
        ['Faroe Islands','234','FO','FRO'],
        ['Fiji','242','FJ','FJI'],
        ['Finland','246','FI','FIN'],
        ['France','250','FR','FRA'],
        ['France Guiana','254','GF','GUF'],
        ['French Polynesia','258','PF','PYF'],
        ['French Southern Territories','260','TF','ATF'],
        ['Gabon','266','GA','GAB'],
        ['Gambia','270','GM','GMB'],
        ['Georgia','268','GE','GEO'],
        ['Germany','280','DE','DEU'],
        ['Ghana','288','GH','GHA'],
        ['Gibraltar','292','GI','GIB'],
        ['Greece','300','GR','GRC'],
        ['Greenland','304','GL','GRL'],
        ['Grenada','308','GD','GRD'],
        ['Guadeloupe','312','GP','GLP'],
        ['Guam','316','GU','GUM'],
        ['Guatemala','320','GT','GTM'],
        ['Guernsey','831','GG','GGY'],
        ['Guinea','324','GN','GIN'],
        ['Guinea – Bissau','624','GW','GNB'],
        ['Guyana','328','GY','GUY'],
        ['Haiti','332','HT','HTI'],
        ['Heard and McDonald Islands','334','HM','HMD'],
        ['Holy See (Vatican City State)','336','VA','VAT'],
        ['Honduras','340','HN','HND'],
        ['Hong Kong','344','HK','HKG'],
        ['Hungary','348','HU','HUN'],
        ['Iceland','352','IS','ISL'],
        ['India','356','IN','IND'],
        ['Indonesia','360','ID','IDN'],
        ['Iran, Islamic Republic Of','364','IR','IRN'],
        ['Iraq','368','IQ','IRQ'],
        ['Ireland','372','IE','IRL'],
        ['Isle of Man','833','IM','IMN'],
        ['Israel','376','IL','ISR'],
        ['Italy','380','IT','ITA'],
        ['Jamaica','388','JM','JAM'],
        ['Japan','392','JP','JPN'],
        ['Jersey','832','JE','JEY'],
        ['Jordan','400','JO','JOR'],
        ['Kazakhstan','398','KZ','KAZ'],
        ['Kenya','404','KE','KEN'],
        ['Kiribati','296','KI','KIR'],
        ['Korea, Demo Peoples Repub of','408','KP','PRK'],
        ['Korea, Republic of','410','KR','KOR'],
        ['Kosovo','900','QZ','QZZ'],
        ['Kuwait','414','KW','KWT'],
        ['Kyrgyzstan','417','KG','KGZ'],
        ['Lao Peoples Democratic Repub','418','LA','LAO'],
        ['Latvia','428','LV','LVA'],
        ['Lebanon','422','LB','LBN'],
        ['Lesotho','426','LS','LSO'],
        ['Liberia','430','LR','LBR'],
        ['Libyan Arab Jamahiriya','434','LY','LBY'],
        ['Liechtenstein','438','LI','LIE'],
        ['Lithuania','440','LT','LTU'],
        ['Luxembourg','442','LU','LUX'],
        ['Macao','446','MO','MAC'],
        ['Macedonia','807','MK','MKD'],
        ['Madagascar','450','MG','MDG'],
        ['Malawi','454','MW','MWI'],
        ['Malaysia','458','MY','MYS'],
        ['Maldives','462','MV','MDV'],
        ['Mali','466','ML','MLI'],
        ['Malta','470','MT','MLT'],
        ['Marshall Islands','584','MH','MHL'],
        ['Martinique','474','MQ','MTQ'],
        ['Mauritania','478','MR','MRT'],
        ['Mauritius','480','MU','MUS'],
        ['Mayotte','175','YT','MYT'],
        ['Mexico','484','MX','MEX'],
        ['Micronesia, Federated States of','583','FM','FSM'],
        ['Moldova, Republic of','498','MD','MDA'],
        ['Monaco','492','MC','MCO'],
        ['Mongolia','496','MN','MNG'],
        ['Montenegro','499','ME','MNE'],
        ['Montserrat','500','MS','MSR'],
        ['Morocco','504','MA','MAR'],
        ['Mozambique','508','MZ','MOZ'],
        ['Myanmar','104','MM','MMR'],
        ['Namibia','516','NA','NAM'],
        ['Nauru','520','NR','NRU'],
        ['Nepal','524','NP','NPL'],
        ['Netherlands','528','NL','NLD'],
        ['Netherlands Antilles','530','AN','ANT'],
        ['New Caledonia','540','NC','NCL'],
        ['New Zealand','554','NZ','NZL'],
        ['Nicaragua','558','NI','NIC'],
        ['Niger','562','NE','NER'],
        ['Nigeria','566','NG','NGA'],
        ['Niue','570','NU','NIU'],
        ['Norfolk Island','574','NF','NFK'],
        ['Northern Mariana Islands','580','MP','MNP'],
        ['Norway','578','NO','NOR'],
        ['Oman','512','OM','OMN'],
        ['Pakistan','586','PK','PAK'],
        ['Palau','585','PW','PLW'],
        ['Palestinian Territory Occupied','275','PS','PSE'],
        ['Panama','591','PA','PAN'],
        ['Papua New Guinea','598','PG','PNG'],
        ['Paraguay','600','PY','PRY'],
        ['Peru','604','PE','PER'],
        ['Philippines','608','PH','PHL'],
        ['Pitcairn','612','PN','PCN'],
        ['Poland','616','PL','POL'],
        ['Portugal','620','PT','PRT'],
        ['Puerto Rico','630','PR','PRI'],
        ['Qatar','634','QA','QAT'],
        ['Republic of South Sudan','728','SS','SSD'],
        ['Reunion','638','RE','REU'],
        ['Romania','642','RO','ROU'],
        ['Russian Federation','643','RU','RUS'],
        ['Rwanda','646','RW','RWA'],
        ['S Georgia S Sandwich Islands','239','GS','SGS'],
        ['Saint Barthelemy','652','BL','BLM'],
        ['Saint Helena','654','SH','SHN'],
        ['Saint Kitts and Nevis','659','KN','KNA'],
        ['Saint Lucia','662','LC','LCA'],
        ['Saint Martin French Part','663','MF','MAF'],
        ['Saint Pierre and Miquelon','666','PM','SPM'],
        ['Samoa','882','WS','WSM'],
        ['San Marino','674','SM','SMR'],
        ['Sao Tome and Principe','678','ST','STP'],
        ['Saudi Arabia','682','SA','SAU'],
        ['Senegal','686','SN','SEN'],
        ['Serbia','688','RS','SRB'],
        ['Seychelles','690','SC','SYC'],
        ['Sierra Leone','694','SL','SLE'],
        ['Singapore','702','SG','SGP'],
        ['Sint Maarten (Dutch Part)','534','SX','SXM'],
        ['Slovakia','703','SK','SVK'],
        ['Slovenia','705','SI','SVN'],
        ['Solomon Islands','090','SB','SLB'],
        ['Somalia','706','SO','SOM'],
        ['South Africa','710','ZA','ZAF'],
        ['Spain','724','ES','ESP'],
        ['Sri Lanka','144','LK','LKA'],
        ['St. Vincent and the Grenadines','670','VC','VCT'],
        ['Sudan','729','SD','SDN'],
        ['Sudan-2','736','YY','YYY'],
        ['Suriname','740','SR','SUR'],
        ['Svalbard and Jan Mayen','744','SJ','SJM'],
        ['Swaziland','748','SZ','SWZ'],
        ['Sweden','752','SE','SWE'],
        ['Switzerland','756','CH','CHE'],
        ['Syrian Arab Republic','760','SY','SYR'],
        ['Taiwan','158','TW','TWN'],
        ['Tajikistan','762','TJ','TJK'],
        ['Tanzania, United Republic of','834','TZ','TZA'],
        ['Thailand','764','TH','THA'],
        ['Timor-Leste','626','TP','TMP'],
        ['Togo','768','TG','TGO'],
        ['Tokelau','772','TK','TKL'],
        ['Tonga','776','TO','TON'],
        ['Trinidad and Tobago','780','TT','TTO'],
        ['Tunisia','788','TN','TUN'],
        ['Turkmenistan','795','TM','TKM'],
        ['Turks and Caicos Is','796','TC','TCA'],
        ['Turkey','792','TR','TUR'],
        ['Tuvalu','798','TV','TUV'],
        ['U.S. Minor Outlying Islands','581','UM','UMI'],
        ['Uganda','800','UG','UGA'],
        ['Ukraine','804','UA','UKR'],
        ['United Arab Emirates','784','AE','ARE'],
        ['United Kingdom','826','GB','GBR'],
        ['United States','840','US','USA'],
        ['Uruguay','858','UY','URY'],
        ['Uzbekistan','860','UZ','UZB'],
        ['Vanuatu','548','VU','VUT'],
        ['Venezuela, Bolivarian Republic','862','VE','VEN'],
        ['Viet Nam','704','VN','VNM'],
        ['Virgin Islands, British','092','VG','VGB'],
        ['Virgin Islands, U.S.','850','VI','VIR'],
        ['Wallis and Futuna','876','WF','WLF'],
        ['Western Sahara','732','EH','ESH'],
        ['Yemen','887','YE','YE'],
        ['Yemen','886','YE','YEM'],
        ['Zambia','894','ZM','ZMB'],
        ['Zimbabwe','716','ZW','ZWE'],
    ];

    const ISO_CURRENCY_CODES = [
        ['Afghani','971','AFN','2','Afghani','Pul'],
        ['Albanian Lek','8','ALL','2','Lekë','Qindarka'],
        ['Algerian Dinar','12','DZD','2','Algerian Dinars','Santīm'],
        ['Argentine Peso','32','ARS','2','Argentine Pesos','Centavos'],
        ['Armenian Dram','51','AMD','2','Armenian Dram','Luma'],
        ['Aruban Florin','533','AWG','2','Aruban Florin','Cents'],
        ['Australian Dollar','36','AUD','2','Australian Dollars','Cents'],
        ['Azerbaijanian Manat','944','AZN','2','Manats','Qəpik'],
        ['Bahamian Dollar','44','BSD','2','Bahamian Dollars','Cents'],
        ['Bahraini Dinar','48','BHD','3','Bahraini Dinars','Fils'],
        ['Baht','764','THB','2','Baht','Satang'],
        ['Balboa','590','PAB','2','Balboas','Centesimos'],
        ['Bangladeshi Taka','50','BDT','2','Takas','Poishas'],
        ['Barbados Dollar','52','BBD','2','Barbados Dollars','Cents'],
        ['Belarussian Ruble','933','BYR','2','Belarussian Rubles','Kapyeyka'],
        ['Belize Dollar','84','BZD','2','Belize Dollars','Cents'],
        ['Bermudian Dollar','60','BMD','2','Bermudan Dollars','Cents'],
        ['Bhutanese Ngultrum','64','BTN','2','Ngultrums','Chetrums'],
        ['Bolivar','937','VEF','2','Bolivares','Centimos'],
        ['Bolívar Soberano','928','VES','2','Bolívares Soberanos','Centimos'],
        ['Boliviano','68','BOB','2','Bolivianos','Centavos'],
        ['Botswana Pula','72','BWP','2','Pula','Thebe'],
        ['Brazilian Real','986','BRL','2','Brazilian Real','Centavos'],
        ['Brunei Dollar','96','BND','2','Brunei Dollars','Cents'],
        ['Bulgarian Lev','975','BGN','2','Lev','Stotinka'],
        ['Burundi Franc','108','BIF','0','Burundi Francs','Centimes'],
        ['Canadian Dollar','124','CAD','2','Canadian Dollars','Cents'],
        ['Cape Verde Escudo','132','CVE','2','Escudos','Centavos'],
        ['Cayman Islands Dollar','136','KYD','2','Cayman Dollars','Cents'],
        ['CFA Franc BCEAO','952','XOF','0','CFA Franc BCEAO','Centimes'],
        ['CFA Franc BEAC','950','XAF','0','CFA Franc BEAC','Centimes'],
        ['CFP Franc','953','XPF','0','CFP Francs','Centimes'],
        ['Chilean Peso','152','CLP','0','Chilean Pesos','Centavos'],
        ['CNH','157','CNH','2','Yuan','Fen'],
        ['CNX','158','CNX','2','Cryptonex',''],
        ['Colombian Peso','170','COP','2','Colombian Pesos','Centavos'],
        ['Comoro Franc','174','KMF','0','Comoro Francs','Centimes'],
        ['Congolese Franc','976','CDF','2','Congolese Francs','Centimes'],
        ['Convertible Mark','977','BAM','2','Convert. Marks','Fenings'],
        ['Cordoba Oro','558','NIO','2','Cordobas','Centavos'],
        ['Costa Rican Colon','188','CRC','2','Costa Rican Colones','Centimos'],
        ['Croatian Kuna','191','HRK','2','Kuna','Lipa'],
        ['Cuban Peso','192','CUP','2','Cuban Pesos','Centavos'],
        ['Czech Koruna','203','CZK','2','Korun','Haler'],
        ['Dalasi','270','GMD','2','Dalasi','Bututs'],
        ['Danish Krone','208','DKK','2','Danish Kroner','Ore'],
        ['Denar','807','MKD','2','Macedonian Denari','Deni'],
        ['Djibouti Franc','262','DJF','0','Djibouti Francs','Centimes'],
        ['Dobra','678','STD','2','Dobras','Centimos'],
        ['Dobra','930','STN','2','Dobra','Centimos'],
        ['Dominican Peso','214','DOP','2','Dominican Pesos','Centavos'],
        ['Dong','704','VND','0','Dong','Hao'],
        ['East Caribbean Dollar','951','XCD','2','East Caribbean Dollars','Cents'],
        ['Egyptian Pound','818','EGP','2','Egyptian Pounds','Piastre'],
        ['El Salvador Colon','222','SVC','2','El Salvador Colones','Centavos'],
        ['ESA','996','ESA','2','Bolívares Soberanos','Céntimos'],
        ['Ethiopian Birr','230','ETB','2','Birr','Santim'],
        ['Euro','978','EUR','2','Euros','Cents'],
        ['Falkland Islands Pound','238','FKP','2','Falkland Pounds','Pence'],
        ['Fiji Dollar','242','FJD','2','Fiji Dollars','Cents'],
        ['Forint','348','HUF','2','Forint','Filler'],
        ['Ghana Cedi','936','GHS','2','Cedis','Pesewa'],
        ['Gibraltar Pound','292','GIP','2','Gibraltar Pounds','Pence'],
        ['Gourde','332','HTG','2','Gourdes','Centimes'],
        ['Guarani','600','PYG','0','Guaranies','Centimos'],
        ['Guinea Franc','324','GNF','0','Guinean Francs','Centimes'],
        ['Guyana Dollar','328','GYD','2','Guyana Dollars','Cents'],
        ['Hong Kong Dollar','344','HKD','2','H.K.Dollars','Cents'],
        ['Hryvnia','980','UAH','2','Hryvnia','Kopiyka'],
        ['Iceland Krona','352','ISK','2','Iceland Krone','Eyrir'],
        ['Indian Rupee','356','INR','2','Indian Rupees','Paise'],
        ['Iraqi Dinar','368','IQD','3','Iraqi Dinars','Fils'],
        ['Jamaican Dollar','388','JMD','2','Jamaican Dollars','Cents'],
        ['Jordanian Dinar','400','JOD','3','Jordanian Dinars','Fils'],
        ['Kenyan Shilling','404','KES','2','Kenyan Shillings','Cents'],
        ['Kina','598','PGK','2','Kina','Toea'],
        ['Kip','418','LAK','2','Kip','Att'],
        ['Kuwaiti Dinar','414','KWD','3','Kuwaiti Dinars','Fils'],
        ['Kwacha','454','MWK','2','Malawi Kwacha','Tambala'],
        ['Kwanza','973','AOA','2','Kwansa','Cents'],
        ['Kyat','104','MMK','2','Kyats','Pyas'],
        ['Kyrgyzstan Soma','417','KGS','2','Som','Tyiyn'],
        ['Lari','981','GEL','2','Georgian Lari','Tetri'],
        ['Lebanese Pound','422','LBP','2','Lebanese Pounds','Qirsh'],
        ['Lempira','340','HNL','2','Lempiras','Centavos'],
        ['Leone','694','SLL','2','Leones','Cents'],
        ['Liberian Dollar','430','LRD','2','Liberian Dollars','Cents'],
        ['Libyan Dinar','434','LYD','3','Libyan Dinars','Dirhams'],
        ['Lilangeni','748','SZL','2','Lilangeni','Cents'],
        ['Loti','426','LSL','2','Maloti','Lisente'],
        ['Malagasy Ariary','969','MGA','2','Madagasc.Ariary','Centimes'],
        ['Malaysian Ringgit','458','MYR','2','Ringgit','Sen'],
        ['Mauritius Rupee','480','MUR','2','Mauritian Rupees','Cents'],
        ['Mexican Peso','484','MXN','2','Mexican Pesos','Centavos'],
        ['Moldovan Leu','498','MDL','2','Moldovan Lei','Ban'],
        ['Moroccan Dirham','504','MAD','2','Moroccan Dirhams','Centimes'],
        ['Mozambique Metical','943','MZN','2','Meticais','Centavos'],
        ['Naira','566','NGN','2','Naira','Kobo'],
        ['Namibia Dollar','516','NAD','2','Namibian Dollars','Cents'],
        ['Nepalese Rupee','524','NPR','2','Nepalese Rupees','Paise'],
        ['Netherlands Antillean Guilder','532','ANG','2','Netherlands Antillean Guilder','Cents'],
        ['New Israeli Sheqel','376','ILS','2','Shekels','Agoras'],
        ['New Romanian Leu','946','RON','2','Romanian Lei','Bani'],
        ['New Taiwan Dollar','901','TWD','2','Taiwan Dollars','Cents'],
        ['New Zealand Dollar','554','NZD','2','N.Zeal.Dollars','Cents'],
        ['Norwegian Krone','578','NOK','2','Norwegian Kroner','Ore'],
        ['Nuevo Sol','604','PEN','2','Sols','Centimos'],
        ['Ouguiya','478','MRO','2','Ouguiya','Khoums'],
        ['Ouguiya','929','MRU','2','Ouguiya','khoums'],
        ['PaÃ¢â‚¬â„¢anga','776','TOP','2','Paanga','Seniti'],
        ['Pakistan Rupee','586','PKR','2','Pakistani Rupees','Paise'],
        ['Pataca','446','MOP','2','Patacas','Avos'],
        ['Peso Uruguayo','858','UYU','2','Pesos Uruguayos','Centesimo'],
        ['Philippine Peso','608','PHP','2','Philippine Pesos','Centavos'],
        ['Pound Sterling','826','GBP','2','Pounds','Pence'],
        ['Qatari Rial','634','QAR','2','Qatari Rials','Dirhams'],
        ['Quetzal','320','GTQ','2','Quetzales','Centavos'],
        ['Rand','710','ZAR','2','Rand','Cents'],
        ['Rial Omani','512','OMR','3','Omani Rials','Baisa'],
        ['Riel','116','KHR','2','Riels','Sens'],
        ['Rufiyaa','462','MVR','2','Rufiyaa','Laari'],
        ['Rupiah','360','IDR','2','Rupiah','Sen'],
        ['Russian Ruble','643','RUB','2','Rubles','Kopeyka'],
        ['Rwanda Franc','646','RWF','0','Rwandan Francs','Centimes'],
        ['Saint Helena Pound','654','SHP','2','St.Helena Pounds','Pence'],
        ['Saudi Riyal','682','SAR','2','Saudi Riyals','Halala'],
        ['Serbian Dinar','941','RSD','2','Serbian Dinars','Paras'],
        ['Seychelles Rupee','690','SCR','2','Seychelles Rupees','Cents'],
        ['Singapore Dollar','702','SGD','2','Singapore Dollars','Cents'],
        ['Solomon Islands dollar','90','SBD','2','Sol.Isl.Dollars','Cents'],
        ['Somali Shilling','706','SOS','2','Somalian Shillings','Senti'],
        ['Somoni','972','TJS','2','Somoni','Diram'],
        ['South Sudanese Pound','728','SSP','2','South Sudanese Pounds','Piasters'],
        ['Sri Lanka Rupee','144','LKR','2','Lankan Rupee','Cents'],
        ['Sudanese Pound','938','SDG','2','Sudanese Pound','Qirsh (Piastre)'],
        ['Surinam Dollar','968','SRD','2','Surinam Dollars','Cents'],
        ['Swedish Krona','752','SEK','2','Swedish Kronor','Ore'],
        ['Swiss Franc','756','CHF','2','Swiss Francs','Rappen'],
        ['Tala','882','WST','2','Tala','Sene'],
        ['Tanzanian Shilling','834','TZS','2','Tanzanian Shilling','Cents'],
        ['Tenge','398','KZT','2','Tenge','Tiyin'],
        ['Trinidad and Tobago Dollar','780','TTD','2','Trinidad and Tobago Dollars','Cents'],
        ['Tugrik','496','MNT','2','Tugrik','Mongo'],
        ['Tunisian Dinar','788','TND','3','Tunisian Dinars','Millimes'],
        ['Turkish Lira','949','TRY','2','Lira','Kurus'],
        ['Turkmenistan New Manat','934','TMT','2','Manats','Tenge'],
        ['UAE Dirham','784','AED','2','UAE Dirhams','Fils'],
        ['Uganda Shilling','800','UGX','0','Ugandan Shillings','Cents'],
        ['Unidades de Fomento','990','CLF','0','Unidades de Fomento',''],
        ['US Dollar','840','USD','2','US Dollars','Cents'],
        ['Uzbekistan Sum','860','UZS','2','Som','Tiyin'],
        ['Vatu','548','VUV','0','Vatu',''],
        ['Won','410','KRW','0','Won','Jeon'],
        ['Yemeni Rial','886','YER','2','Yemeni Rials','Fils'],
        ['Yen','392','JPY','0','Yen','Sen'],
        ['Yuan Renminbi','156','CNY','2','Renminbi','Fen'],
        ['Zambian Kwacha','967','ZMW','2','Zambian Kwacha','Ngwee'],
        ['Zloty','985','PLN','2','Zloty','Grosz'],
    ];

    /**
     * Get the Currency Code for a given needle
     * 
     * @param int|string $needle
     * 
     * @return int|NULL
     */
    public static function getCurrencyCode($needle)
    {
        $out = self::search($needle, self::ISO_CURRENCY_CODES);
        return is_array($out) ? self::ISO_CURRENCY_CODES[$out[0]][1] : NULL;
    }

    /**
     * Get the Country Code for a given needle
     * 
     * @param int|string $needle
     * 
     * @return int|NULL
     */
    public static function getCountryCode($needle)
    {
        $out = self::search($needle, self::ISO_COUNTRY_CODES);
        return is_array($out) ? self::ISO_COUNTRY_CODES[$out[0]][1] : NULL;
    }

    /**
     * Find row and column of needle in the haystack
     * 
     * @param int|string $needle
     * @param array $haystack
     * 
     * @return array|bool
     */
    private static function search($needle, $haystack)
    {
        $row = 0;
        foreach($haystack as $bushel)
        {
            if($col = array_search($needle, $bushel))
                return [$row, $col];
            $row++;
        }

        return false;
    }
}